---
- name: Commit and reload system
  community.openwrt.uci:
    command: commit
    key: system
  notify: Reload system service

- name: Reload system service
  community.openwrt.service:
    name: system
    state: reloaded
  changed_when: false

- name: Commit and restart dnsmasq
  community.openwrt.uci:
    command: commit
    key: dhcp
  notify: Restart dnsmasq service

- name: Restart dnsmasq service
  community.openwrt.service:
    name: dnsmasq
    state: restarted
  changed_when: false

- name: Commit and reload firewall
  community.openwrt.uci:
    command: commit
    key: firewall
  notify: Reload firewall service

- name: Reload firewall service
  community.openwrt.service:
    name: firewall
    state: reloaded
  changed_when: false

- name: Commit and reload wifi
  community.openwrt.uci:
    command: commit
    key: wireless
  notify: Reload wifi service

- name: Reload wifi service
  community.openwrt.command:
    cmd: wifi up
  changed_when: false

- name: Commit and restart network
  community.openwrt.uci:
    command: commit
    key: network
  notify: Restart network service

- name: Restart network service
  community.openwrt.service:
    name: network
    state: restarted
  changed_when: false

- name: Commit and restart unbound
  community.openwrt.uci:
    command: commit
    key: unbound
  notify: Restart unbound service

- name: Restart unbound service
  community.openwrt.service:
    name: unbound
    state: restarted
  changed_when: false
