# IT-Tools defaults

# Image
it_tools_image_name: "ghcr.io/sharevb/it-tools"
it_tools_image_tag: "latest"

# Paths
it_tools_opt_dir: "{{ ansible_opt_base }}/it_tools"

# CNAME subdomain (without .{{ lan_domain }})
it_tools_cname: "it.tools"
