---
- name: Configure LAN DHCP
  community.openwrt.uci:
    command: set
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: dhcp.@dnsmasq[0].domain
      value: "{{ lan_domain }}"
    - key: dhcp.lan.start
      value: "{{ lan_dhcp_start }}"
    - key: dhcp.lan.limit
      value: "{{ lan_dhcp_limit }}"
    - key: dhcp.lan.leasetime
      value: "{{ lan_dhcp_leasetime }}"
  notify: Commit and restart dnsmasq

- name: Configure IoT DHCP
  community.openwrt.uci:
    command: set
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: dhcp.iot
      value: dhcp
    - key: dhcp.iot.interface
      value: iot
    - key: dhcp.iot.start
      value: "{{ iot_dhcp_start }}"
    - key: dhcp.iot.limit
      value: "{{ iot_dhcp_limit }}"
    - key: dhcp.iot.leasetime
      value: "{{ iot_dhcp_leasetime }}"
  notify: Commit and restart dnsmasq

- name: Add DHCP reservations
  community.openwrt.uci:
    command: section
    config: dhcp
    type: host
    name: "{{ item.name }}"
    find:
      mac: "{{ item.mac }}"
    value:
      mac: "{{ item.mac }}"
      ip: "{{ item.ip }}"
    replace: true
  loop: "{{ dhcp_reservations }}"
  notify: Commit and restart dnsmasq

- name: Add DNS CNAMEs
  community.openwrt.uci:
    command: section
    config: dhcp
    type: cname
    name: "{{ item.cname | regex_replace('[^a-zA-Z0-9_]', '_') }}"
    find:
      cname: "{{ item.cname }}"
    value:
      cname: "{{ item.cname }}"
      target: "{{ item.target }}"
    replace: true
  loop: "{{ dns_cnames }}"
  notify: Commit and restart dnsmasq
