---
- name: Disable IPv6
  community.openwrt.uci:
    command: set
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: network.wan6.disabled
      value: "1"
    - key: network.wan.ipv6
      value: "0"
    - key: network.lan.ip6assign
      value: "0"
    - key: network.lan.ip6table
      value: "0"
    - key: dhcp.lan.dhcpv6
      value: disabled
    - key: dhcp.lan.ra
      value: disabled
  when: lan_ipv6_disabled | default(false)
  notify: Commit and restart network

- name: Configure IoT interface
  community.openwrt.uci:
    command: section
    config: network
    type: interface
    name: iot
    find: {}
    value:
      proto: static
      type: bridge
      ipaddr: "{{ iot_ip }}"
      netmask: "{{ iot_netmask }}"
    replace: true
  notify: Commit and restart network

- name: Commit and reload network
  community.openwrt.uci:
    command: commit
    key: network
  changed_when: true

- name: Reload network
  community.openwrt.command:
    cmd: /etc/init.d/network reload
  changed_when: true
