---
- name: Set timezone
  community.openwrt.uci:
    command: set
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "system.@system[0].timezone", value: "{{ openwrt_timezone }}" }
    - { key: "system.@system[0].zonename", value: "{{ timezone }}" }
  notify: Commit and reload system
