---
- name: Delete default wifi interfaces
  community.openwrt.uci:
    command: delete
    key: "wireless.{{ item }}"
  loop:
    - default_radio0
    - default_radio1
  failed_when: false
  notify: Commit and reload wifi

- name: Configure wifi radios
  community.openwrt.uci:
    command: section
    config: wireless
    type: wifi-device
    name: "{{ item.name }}"
    find: {}
    value:
      country: "{{ wifi_country }}"
      band: "{{ item.band }}"
      htmode: "{{ item.htmode }}"
      channel: "{{ item.channel }}"
      disabled: "0"
    replace: true
  loop: "{{ wifi_radios }}"
  loop_control:
    label: "{{ item.name }}"
  notify: Commit and reload wifi

- name: Configure wifi interfaces
  community.openwrt.uci:
    command: section
    config: wireless
    type: wifi-iface
    name: "{{ item.name }}"
    find:
      device: "{{ item.radio }}"
    value:
      device: "{{ item.radio }}"
      mode: ap
      network: "{{ item.network }}"
      ssid: "{{ item.ssid }}"
      encryption: "{{ item.encryption }}"
      key: "{{ item.password }}"
      hidden: "{{ '1' if item.hidden else '0' }}"
    replace: true
  loop: "{{ wifi_interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  no_log: true
  notify: Commit and reload wifi
